name: Build Linux y Windows

on: [push]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.3'
      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-cursor0 libxcb-cursor-dev
      - name: Compilar
        run: |
          qmake -config release
          make -j4
      - name: Eliminar drivers SQL no usados
        run: |
          rm -f "${{ env.Qt6_DIR }}/plugins/sqldrivers/libqsqlmimer.so"
          rm -f "${{ env.Qt6_DIR }}/plugins/sqldrivers/libqsqlodbc.so"
          rm -f "${{ env.Qt6_DIR }}/plugins/sqldrivers/libqsqlpsql.so"
      - name: Crear archivo .desktop
        run: |
          cat > SeguridadGolden.desktop << 'DESKTOP_EOF'
          [Desktop Entry]
          Type=Application
          Name=SeguridadGolden
          Exec=SeguridadGolden
          Icon=SeguridadGolden
          Categories=Utility;
          DESKTOP_EOF
      - name: Descargar linuxdeployqt
        run: |
          wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod +x linuxdeployqt-continuous-x86_64.AppImage
      - name: Empaquetar AppImage
        run: |
          export QML_SOURCES_PATHS=.
          ./linuxdeployqt-continuous-x86_64.AppImage SeguridadGolden.desktop -appimage -no-translations
        env:
          QMAKE: ${{ env.Qt6_DIR }}/bin/qmake
      - name: Subir ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: SeguridadGolden-Linux
          path: '*.AppImage'

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.3'
      - name: Configurar entorno MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compilar
        run: |
          qmake -config release
          nmake
      - name: Empaquetar DLLs
        run: windeployqt release\SeguridadGolden.exe
      - name: Subir ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: SeguridadGolden-Windows
          path: release\
